import{open,lstat}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';
import{selectAccount,type Account,type Config}from'../config.js';import{CreatomateError,UsageError}from'./errors.js';
export type Json=Record<string,any>;export type QueryParam={name:string;value:unknown};const MAX=5*1048576;
export class CreatomateClient{
 private tokens=new Map<string,string>();private schedule:Promise<void>=Promise.resolve();private nextAt=0;
 constructor(readonly config:Config,private readonly fetcher:typeof fetch=fetch,private readonly sleep:(ms:number)=>Promise<void>=ms=>new Promise(r=>setTimeout(r,ms))){}
 redactText(text:string){for(const secret of [...this.config.accounts.map(a=>a.apiToken),...this.tokens.values()].filter(Boolean).sort((a,b)=>b.length-a.length))text=text.split(secret).join('[redacted]');return text.replace(/https?:\/\/[^\s"<>]*(?:X-Amz-Signature|[?&](?:token|signature|sig|key|access_token)=)[^\s"<>]*/gi,'[private credential URL]');}
 sanitize(v:unknown):unknown{if(typeof v==='string')return this.redactText(v);if(Array.isArray(v))return v.map(x=>this.sanitize(x));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,/^(password|secret|api_key|signing_key|api_token|token|access_token|refresh_token|authorization|client_secret)$/i.test(k)?'[redacted]':this.sanitize(x)]));return v;}
 private async token(a:Account){if(this.tokens.has(a.name))return this.tokens.get(a.name)!;let token=a.apiToken;if(a.tokenFile){let file;try{if(!isAbsolute(a.tokenFile))throw Error();if(!(await lstat(a.tokenFile)).isFile())throw Error();file=await open(a.tokenFile,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await file.stat();if(!stat.isFile()||stat.size>65536||(process.platform!=='win32'&&((stat.mode&0o077)||stat.uid!==process.getuid?.())))throw Error();token=(await file.readFile('utf8')).trim();}catch{throw new CreatomateError('Cannot read the private Creatomate token file; use an absolute owner-only regular token-only file at most 64 KiB.',0,'CONFIG');}finally{await file?.close();}}if(!token||/[\r\n]/.test(token))throw new CreatomateError('No valid API key configured for the selected project profile. Run creatomate-cli login.',0,'CONFIG');this.tokens.set(a.name,token);return token;}
 private async pace(_a:Account){const next=this.schedule.catch(()=>{}).then(async()=>{const delay=Math.max(0,this.nextAt-Date.now());if(delay)await this.sleep(delay);this.nextAt=Date.now()+this.config.minIntervalMs;});this.schedule=next;await next;}
 private async bytes(response:Response){const chunks:Uint8Array[]=[];let total=0;const reader=response.body?.getReader();if(reader)try{for(;;){const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>MAX){await reader.cancel();throw new CreatomateError('Response exceeds the 5 MiB local cap; no automatic retry.');}chunks.push(part.value);}}finally{reader.releaseLock();}return Buffer.concat(chunks);}
 async request(method:string,path:string,query:QueryParam[]=[],body?:Json,hint?:string):Promise<Json>{
  const valid=/^\/v2\/(?:renders(?:\/[A-Za-z0-9_-]+)?|templates(?:\/[A-Za-z0-9_-]+)?)$/.test(path)||/^\/v1\/(?:renders|feeds(?:\/[A-Za-z0-9_-]+(?:\/sample)?)?)$/.test(path);
  const allowed=method==='GET'&&(/^\/v2\/(?:templates(?:\/[^/]+)?|renders\/[^/]+)$/.test(path)||path.startsWith('/v1/feeds'))||method==='POST'&&['/v2/renders','/v2/templates','/v1/renders'].includes(path)||['PATCH','DELETE'].includes(method)&&/^\/v2\/templates\/[^/]+$/.test(path);
  if(!valid||!allowed)throw new UsageError('Unsupported Creatomate API method or path.');
  for(const p of query)if(path!=='/v2/templates'||p.name!=='tags'||typeof p.value!=='string')throw new UsageError('Unsupported Creatomate query parameter.');
  const a=selectAccount(this.config,hint),url=new URL(path,'https://api.creatomate.com');for(const p of query)url.searchParams.set(p.name,String(p.value));
  const headers:Record<string,string>={Accept:'application/json',Authorization:'Bearer '+await this.token(a)};
  const encoded=body===undefined?undefined:JSON.stringify(body);if(encoded!==undefined){if(Buffer.byteLength(encoded)>1048576)throw new UsageError('Request exceeds 1 MiB JSON limit.');headers['Content-Type']='application/json';}
  await this.pace(a);let response:Response;try{response=await this.fetcher(url,{method,redirect:'error',signal:AbortSignal.timeout(this.config.timeoutMs),headers,...(encoded===undefined?{}:{body:encoded})});}catch{throw new CreatomateError('Creatomate request failed or timed out. Its outcome may be unknown; no automatic retry. Inspect provider state before deliberately repeating.',0,'NETWORK');}
  const text=(await this.bytes(response)).toString('utf8');if(!response.ok){let detail='';try{detail=JSON.stringify(this.sanitize(JSON.parse(text))).slice(0,1000);}catch{}const quota=response.status===429||response.status===402;throw new CreatomateError('Creatomate API '+response.status+(quota?' rate limit or insufficient credits':'')+(detail?': '+detail:''),response.status,quota?'RATE_LIMIT':response.status===401||response.status===403?'AUTH':'API_ERROR');}
  if(response.status===204)return{status:204,deleted:true};
  let parsed;try{parsed=JSON.parse(text);}catch{throw new CreatomateError('Creatomate returned a non-JSON response; no automatic retry.');}if(parsed===null||typeof parsed!=='object')throw new CreatomateError('Invalid Creatomate JSON response.');return this.sanitize(parsed)as Json;
 }
}
