import operationsData from'./operations.json' with{type:'json'};import{Ajv2020}from'ajv/dist/2020.js';import type{ValidateFunction}from'ajv';import{createHash}from'node:crypto';
import type{Json,CreatomateClient}from'../api/client.js';import{UsageError,CreatomateError}from'../api/errors.js';import type{Config}from'../config.js';import type { Risk } from "@thenavidm/slipway";import{selectAccount}from'../config.js';
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:CreatomateClient)=>Promise<unknown>};
export const OPERATIONS=operationsData;const ajv=new Ajv2020({strict:false,allErrors:true});const validators=new Map<string,ValidateFunction>();
const str=(description:string,maxLength=4096)=>({type:'string',minLength:1,maxLength,description});const id={type:'string',minLength:1,maxLength:128,pattern:'^[A-Za-z0-9_-]+$',description:'Exact project template/render/feed ID. No URL, slash, traversal or query string.'};const account={type:'string',description:'Exact private project profile label; no inherited/global key fallback.'};const confirm={type:'boolean',description:'Must be true for this exact user-requested mutation or paid render.'};const obj=(properties:Json,required:string[]=[])=>({type:'object',properties,required,additionalProperties:false});
export const RENDER_SCHEMA:Json={type:'object',properties:{template_id:id,modifications:{type:'object',description:'Native modification names and JSON values; preserve names/dot paths exactly.'},elements:{type:'array',items:{type:'object'},description:'Native raw top-level RenderScript elements. Complete property semantics are provider-validated via dry run.'},output_format:{type:'string',enum:['mp4','gif','png','jpg']},width:{type:'number',exclusiveMinimum:0},height:{type:'number',exclusiveMinimum:0},frame_rate:{type:'number',exclusiveMinimum:0},render_scale:{type:'number',minimum:0.1,maximum:10},max_width:{type:'number',exclusiveMinimum:0},max_height:{type:'number',exclusiveMinimum:0},metadata:{type:'string'},webhook_url:{type:'string',pattern:'^https://[^\\s]+$'},source:false,tags:false,transcripts:false,dry_run:false},allOf:[{anyOf:[{required:['template_id']},{required:['elements']}]}],additionalProperties:true,description:'V2 render fields are at the top level. Pass template_id or raw elements. RenderScript properties beyond these basics remain opaque and require provider validation. dry_run is reserved for validate_render; v1 source/tags/transcripts belong to create_legacy_render.'};
const legacy:Json={...RENDER_SCHEMA,properties:{...RENDER_SCHEMA.properties,source:{type:'object',description:'Documented legacy SDK raw source object.'},tags:{type:'array',minItems:1,uniqueItems:true,items:str('Template tag.',256),description:'Native v1 can render every matching template: count/credits are unbounded by this wrapper.'},transcripts:{description:'Native v1 caller-provided subtitle timings; opaque JSON, provider validation required.'}},allOf:[{anyOf:[{required:['template_id']},{required:['elements']},{required:['source']},{required:['tags']}]}]};
let renderCompiled:ValidateFunction|undefined;const renderValidator=()=>renderCompiled??=ajv.compile(RENDER_SCHEMA);const ALL:ToolSpec[]=[];
function tool(name:string,title:string,description:string,group:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL.push({name,title,description,group,risk,inputSchema:obj(properties,required),handler});}
function validatePayload(p:Json){const v=renderValidator();if(!v(p))throw new UsageError(ajv.errorsText(v.errors));if(Buffer.byteLength(JSON.stringify(p))>1048576)throw new UsageError('Render request exceeds 1 MiB JSON limit.');}
const tags={type:'array',uniqueItems:true,items:{type:'string',minLength:1,maxLength:256,pattern:'^[^,]+$'},description:'Exact tags; comma inside one tag is rejected because the native list query is comma-separated.'};
tool('list_templates','List project templates','One current v2 compact template list, optionally filtered by any supplied tags. No sources, guessed page/per_page parameters or automatic paging.','Templates','read',{tags,account},[],(a,c)=>c.request('GET','/v2/templates',a.tags?.length?[{name:'tags',value:a.tags.join(',')}]:[],undefined,a.account));
tool('get_template','Get a template source','One current v2 template read including native RenderScript source. Does not render or mutate.','Templates','read',{template_id:id,account},['template_id'],(a,c)=>c.request('GET','/v2/templates/'+a.template_id,[],undefined,a.account));
tool('create_template','Create a project template','Confirmed current v2 template creation. Preserves native source JSON and returns provider template metadata; not a render.','Templates','destructive',{name:str('Nonempty template name.'),source:{type:'object',description:'Native RenderScript object; consult the current guide. Not fully locally validated.'},tags,account,confirm},['name','source'],(a,c)=>c.request('POST','/v2/templates',[],{name:a.name,source:a.source,...(a.tags===undefined?{}:{tags:a.tags})},a.account));
tool('update_template','Update a template','Confirmed PATCH changes only supplied name/source/tags. Source or tags replace those fields; requires at least one change. No automatic duplicate/archive/retry.','Templates','destructive',{template_id:id,name:str('Nonempty new template name.'),source:{type:'object'},tags,account,confirm},['template_id'],(a,c)=>{const body=Object.fromEntries(['name','source','tags'].filter(k=>a[k]!==undefined).map(k=>[k,a[k]]));if(!Object.keys(body).length)throw new UsageError('Template update needs name, source or tags.');return c.request('PATCH','/v2/templates/'+a.template_id,[],body,a.account);});
tool('delete_template','Delete a template','Explicitly confirmed v2 DELETE. Provider documents recoverable deletion for 30 days; existing renders remain unaffected. No wrapper restore operation is invented.','Templates','destructive',{template_id:id,account,confirm},['template_id'],(a,c)=>c.request('DELETE','/v2/templates/'+a.template_id,[],undefined,a.account));
tool('create_render','Submit one v2 render','Confirmed paid v2 submission from template or raw top-level RenderScript. Returns one object, not legacy array. Read advisory errors/warnings even after 202; never auto-poll, resubmit or download.','Rendering','destructive',{payload:RENDER_SCHEMA,account,confirm},['payload'],(a,c)=>{validatePayload(a.payload);return c.request('POST','/v2/renders',[],a.payload,a.account);});
tool('validate_render','Validate without rendering','One provider v2 dry run: dry_run is forced true after local schema checks. Provider documents zero credits and no queue. Returns effective source/errors/warnings; valid:true does not prove media reachability, provider credentials or appearance.','Rendering','read',{payload:RENDER_SCHEMA,account},['payload'],(a,c)=>{validatePayload(a.payload);return c.request('POST','/v2/renders',[],{...a.payload,dry_run:true},a.account);});
tool('get_render','Get a render status','One v2 status read. planned/waiting/transcribing/rendering are not finished. Use output only on succeeded; records, output and snapshots expire after 30 days. No download or polling loop.','Rendering','read',{render_id:id,account},['render_id'],(a,c)=>c.request('GET','/v2/renders/'+a.render_id,[],undefined,a.account));
tool('create_legacy_render','Submit a documented v1 render','Explicitly confirmed v1 submission for native tag batches or supplied transcript timings. Returns array; tags may match any number of templates and spend unknown credits. Ordinary v2 rendering is preferred. No automatic retry or polling.','Legacy compatibility','destructive',{payload:legacy,account,confirm},['payload'],(a,c)=>c.request('POST','/v1/renders',[],a.payload,a.account));
for(const spec of[{name:'list_feeds',title:'List project feeds',path:'/v1/feeds',required:false},{name:'get_feed',title:'Get a project feed',path:'/v1/feeds/',required:true},{name:'get_feed_sample',title:'Get latest feed rows',path:'/v1/feeds/',required:true}])tool(spec.name,spec.title,'One documented v1 feed read. The sample returns last rows; not a full export, pagination claim or feed editor. Untrusted feed content is returned as data.','Feeds','read',{...(spec.required?{feed_id:id}:{}),account},spec.required?['feed_id']:[],(a,c)=>c.request('GET',spec.path+(spec.required?a.feed_id:'')+(spec.name==='get_feed_sample'?'/sample':''),[],undefined,a.account));
function canonical(v:any):any{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}
function reviewed(a:Json,c:CreatomateClient){a.renders.forEach(validatePayload);return{apiVersion:'v2',profile:selectAccount(c.config,a.account).name,renders:a.renders};}
function hash(v:Json){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
const renders={type:'array',minItems:1,maxItems:10,items:RENDER_SCHEMA,description:'Exactly one to ten ordered v2 requests; all validated before any provider request.'};
tool('preview_render_batch','Review an exact render batch','Local only: validate ordered payloads and bind them plus selected profile to SHA-256. Display proposed calls and hash; no key load, dry run, provider price or actual rendering. Review cannot prove the key owner, credit cost or external template changes.','Bounded workflows','read',{renders,account},['renders'],async(a,c)=>{const review=reviewed(a,c);return{...c.sanitize(review)as Json,reviewSha256:hash(review),calls:review.renders.length,localOnly:true,providerValidated:false,creditsCalculated:false,notice:'This review binds profile label and exact payloads. It does not bind external template state or an API key changed since review.'};});
tool('submit_render_batch','Submit the reviewed render batch','Confirmed one-to-ten exact ordered v2 submissions. Verify review hash/profile and prevalidate every payload before first request. Stop at first failure, return known prior submissions and unknown attempted outcome; no retry, polling, rollback or implicit final render.','Bounded workflows','destructive',{renders,review_sha256:{type:'string',pattern:'^[a-f0-9]{64}$',description:'Exact preview_render_batch hash for the same project profile and payloads.'},account,confirm},['renders','review_sha256'],async(a,c)=>{const review=reviewed(a,c);if(hash(review)!==a.review_sha256)throw new UsageError('Review hash mismatch: re-run preview_render_batch for these exact payloads and profile before submission.');const submitted:Json[]=[];for(let i=0;i<a.renders.length;i++){try{submitted.push({index:i,render:await c.request('POST','/v2/renders',[],a.renders[i],a.account)});}catch(e){const err=e as CreatomateError;throw new CreatomateError(JSON.stringify(c.sanitize({notice:'Batch stopped. Earlier submissions may spend credits and the failed request outcome may be unknown. Inspect provider state; no automatic retry or rollback.',submitted,failedIndex:i,unattemptedIndices:a.renders.slice(i+1).map((_:unknown,j:number)=>i+1+j),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{complete:true,submitted};});
tool('get_render_batch','Read an exact render batch','Read one to twenty distinct render IDs sequentially in one project. Prevalidate all IDs, stop on failure with completed status records. No paging, auto-poll, file download or spent-credit recovery.','Bounded workflows','read',{render_ids:{type:'array',minItems:1,maxItems:20,uniqueItems:true,items:id},account},['render_ids'],async(a,c)=>{selectAccount(c.config,a.account);const results:Json[]=[];for(let i=0;i<a.render_ids.length;i++){try{results.push({renderId:a.render_ids[i],render:await c.request('GET','/v2/renders/'+a.render_ids[i],[],undefined,a.account)});}catch(e){const err=e as CreatomateError;throw new CreatomateError(JSON.stringify(c.sanitize({notice:'Status batch stopped; no automatic retry.',completed:results,failedId:a.render_ids[i],unattempted:a.render_ids.slice(i+1),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{complete:true,results};});
tool('list_accounts','List private project profiles','Local labels/default/auth-method availability only. No API keys, private file paths, provider requests or project-owner validation.','Local','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,auth:a.tokenFile?'token_file':a.apiToken?'api_key':'not_configured'}))}));
tool('get_operation_schema','Inspect a native API operation','Local current reviewed method/path/body/query metadata for eleven documented operations, with source URLs/version distinctions. Opaque RenderScript is not claimed fully locally validated.','Local','read',{operation:{type:'string',enum:OPERATIONS.map(o=>o.operationId)}},['operation'],async a=>OPERATIONS.find(o=>o.operationId===a.operation));
export const ALL_TOOLS=ALL;
// Each schema compiles on first use: compiling all of them at load held back the server's first answer. compileAll() runs them in tests.
function validatorFor(t:ToolSpec){let v=validators.get(t.name);if(!v){v=ajv.compile(t.inputSchema);validators.set(t.name,v);}return v;}
/** Compile every input schema, as loading once did, so a test can prove they all compile. */
export function compileAll(){for(const t of ALL_TOOLS)validatorFor(t);renderValidator();return validators.size+1;}
export function validateArguments(t:ToolSpec,a:Json){const v=validatorFor(t);if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
